import unicodeEmojis from './emoji-data/catalog.json' with { type: 'json' };

// Names double as accessible labels; keywords make work-related searches discoverable.
const preferredEmojis = [
  { emoji: '💻', name: 'Laptop', keywords: 'computer coding programming working developer' },
  { emoji: '🎯', name: 'Bullseye', keywords: 'target focus goals concentrating' },
  { emoji: '📝', name: 'Memo', keywords: 'writing notes document planning' },
  { emoji: '📚', name: 'Books', keywords: 'reading learning studying research' },
  { emoji: '🎨', name: 'Artist palette', keywords: 'art design creative drawing' },
  { emoji: '🔧', name: 'Wrench', keywords: 'fix repair tools maintenance debugging' },
  { emoji: '💬', name: 'Speech bubble', keywords: 'chat talking discussion meeting' },
  { emoji: '☕', name: 'Coffee', keywords: 'tea hot beverage break cafe' },
  { emoji: '🍽️', name: 'Plate with cutlery', keywords: 'lunch dinner eating food meal' },
  { emoji: '🌴', name: 'Palm tree', keywords: 'vacation holiday tropical away' },
  { emoji: '🏠', name: 'House', keywords: 'home remote working' },
  { emoji: '🚀', name: 'Rocket', keywords: 'launch shipping deploy release' },
  { emoji: '😀', name: 'Grinning face', keywords: 'happy smile cheerful' },
  { emoji: '😊', name: 'Smiling face', keywords: 'happy pleased grateful' },
  { emoji: '😎', name: 'Sunglasses face', keywords: 'cool sunny relaxed' },
  { emoji: '🤔', name: 'Thinking face', keywords: 'ponder question problem solving' },
  { emoji: '😴', name: 'Sleeping face', keywords: 'sleep tired nap rest' },
  { emoji: '🤒', name: 'Thermometer face', keywords: 'sick ill unwell health' },
  { emoji: '🥳', name: 'Partying face', keywords: 'celebrate birthday party' },
  { emoji: '🫠', name: 'Melting face', keywords: 'overwhelmed hot busy' },
  { emoji: '👋', name: 'Waving hand', keywords: 'hello goodbye greeting' },
  { emoji: '👍', name: 'Thumbs up', keywords: 'yes good approved okay' },
  { emoji: '🙌', name: 'Raised hands', keywords: 'hooray success celebration' },
  { emoji: '❤️', name: 'Red heart', keywords: 'love care favorite' },
  { emoji: '✨', name: 'Sparkles', keywords: 'magic shiny new polish' },
  { emoji: '🔥', name: 'Fire', keywords: 'hot urgent incident' },
  { emoji: '🎉', name: 'Party popper', keywords: 'celebration congratulations milestone' },
  { emoji: '🎧', name: 'Headphones', keywords: 'music listening focus audio' },
  { emoji: '📞', name: 'Telephone', keywords: 'call phone meeting' },
  { emoji: '📹', name: 'Video camera', keywords: 'video recording meeting call' },
  { emoji: '📅', name: 'Calendar', keywords: 'schedule appointment meeting' },
  { emoji: '💡', name: 'Light bulb', keywords: 'idea brainstorm thinking' },
  { emoji: '🔍', name: 'Magnifying glass', keywords: 'search review investigate research' },
  { emoji: '🐛', name: 'Bug', keywords: 'debug testing fix error' },
  { emoji: '🧪', name: 'Test tube', keywords: 'experiment science testing lab' },
  { emoji: '🛠️', name: 'Hammer and wrench', keywords: 'building engineering tools' },
  { emoji: '🔒', name: 'Lock', keywords: 'private security secure' },
  { emoji: '📊', name: 'Bar chart', keywords: 'analytics data metrics report' },
  { emoji: '✅', name: 'Check mark', keywords: 'done complete finished ready' },
  { emoji: '⏳', name: 'Hourglass', keywords: 'waiting time pending' },
  { emoji: '🚶', name: 'Walking person', keywords: 'walk break away outside' },
  { emoji: '🏃', name: 'Running person', keywords: 'run exercise workout gym' },
  { emoji: '🚲', name: 'Bicycle', keywords: 'bike commute cycling' },
  { emoji: '🚗', name: 'Car', keywords: 'driving commute travel' },
  { emoji: '✈️', name: 'Airplane', keywords: 'flight travel trip away' },
  { emoji: '🌱', name: 'Seedling', keywords: 'growth garden nature learning' },
  { emoji: '🌞', name: 'Sun', keywords: 'sunny morning weather outside' },
  { emoji: '🍕', name: 'Pizza', keywords: 'food lunch eating break' },
  { emoji: '🍵', name: 'Teacup', keywords: 'tea matcha drink break' },
  { emoji: '🐶', name: 'Dog', keywords: 'pet puppy walking' },
  { emoji: '🐱', name: 'Cat', keywords: 'pet kitten' },
  { emoji: '👶', name: 'Baby', keywords: 'child family parenting' },
] as const;

const preferred = new Set<string>(preferredEmojis.map((entry) => entry.emoji));
export const statusEmojiCatalog = [
  ...preferredEmojis,
  ...unicodeEmojis.filter((entry) => !preferred.has(entry.emoji)),
];
export const statusEmojis = statusEmojiCatalog.map((entry) => entry.emoji) as [string, ...string[]];
