"""Original 24x32 pixel characters, exported at 4x with registered wardrobe layers.

All parts share the same foot anchor, direction and gait. The wardrobe editor
composes independent style and palette atlases generated by generate-wardrobe.py.
"""
from draw import Image, Rect, Poly, fill, rgb, shift

W, H = 96, 128
DIRECTIONS = ('down', 'left', 'right', 'up')
FRAMES = 3
LAYERS = ('hair_back', 'body', 'pants', 'shoes', 'shirt', 'hands', 'head', 'hair', 'accessory', 'hat')
SKINS = ['f0d3b4', 'e3bd96', 'c58c5f', '9c6b47', '6f4a32', 'd8a97f']
HAIRS = ['3b2f2a', '8c5a34', '1f1a17', 'c9a24d', '5f4136', 'a0402e', '5f6f8c', 'd9d2c4']
INK = rgb('3e3035')


def rect(img, x, y, w, h, c):
    fill(img, Rect(x * 4, y * 4, w * 4, h * 4), c)


def poly(img, points, c):
    fill(img, Poly([(x * 4, y * 4) for x, y in points]), c)


def box(img, x, y, w, h, c):
    rect(img, x, y, w, h, INK)
    rect(img, x + 1, y + 1, w - 2, h - 2, c)


def flip(src):
    out = Image(src.w, src.h)
    for y in range(src.h):
        for x in range(src.w):
            i, j = (y * src.w + x) * 4, (y * src.w + src.w - 1 - x) * 4
            out.px[i:i + 4] = src.px[j:j + 4]
    return out


def frame_layers(spec, direction, frame):
    if direction == 'left':
        return {name: flip(img) for name, img in frame_layers(spec, 'right', frame).items()}
    layers = {name: Image(W, H) for name in LAYERS}
    side, back = direction == 'right', direction == 'up'
    walk = (-1, 0, 1)[frame]
    bob = 0 if frame == 1 else -1
    skin, hair = rgb(spec['skin']), rgb(spec['hair'])
    shirt, pants, shoe = rgb(spec['top']), rgb(spec['bottom']), rgb(spec['shoes'])
    hd, hl = shift(hair, -0.25), shift(hair, 0.28)
    style = spec['hair_style']
    # Long hair sits behind the shoulders; hats never replace the hair selection.
    img = layers['hair_back']
    if style in ('bob', 'long', 'wavy', 'ponytail'):
        if style == 'ponytail':
            box(img, 5 if side else 14, 9 + bob, 5, 12, hair)
            rect(img, 6 if side else 15, 10 + bob, 1, 8, hl)
        else:
            box(img, 5, 7 + bob, 14, 14 if style != 'bob' else 10, hd)
            rect(img, 6, 9 + bob, 2, 10 if style != 'bob' else 6, hair)
            rect(img, 17, 9 + bob, 1, 10 if style != 'bob' else 6, hl)
    # In profile the legs overlap at rest and stride along the facing axis.
    # Share these anchors across skin, trousers and footwear so all combinations
    # turn together. Draw the far leg first, with slightly darker shading.
    legs = ((11 - walk * 2, min(walk, 0), -0.18),
            (12 + walk * 2, min(-walk, 0), 0)) if side else (
                (8, walk, 0), (13, -walk, 0))
    # Bare body, trousers and shoes have independent registration.
    img = layers['body']
    rect(img, 10, 13 + bob, 4, 5, shift(skin, -0.16))
    for x, lift, shade in legs:
        c = shift(skin, shade)
        box(img, x, 23, 4, 7 + lift, c)
        rect(img, x + (1 if side else 0), 28 + lift, 4 if side else 3, 2, c)
    img = layers['pants']
    if spec.get('bottom_style') == 'skirt':
        left, right = (10, 16) if side else (8, 16)
        poly(img, [(left, 22 + bob), (right, 22 + bob), (right + 2, 27), (left - 2, 27)], INK)
        poly(img, [(left + 1, 22 + bob), (right - 1, 22 + bob), (right, 26), (left, 26)], pants)
        rect(img, left + 1, 24, 1, 2, shift(pants, 0.25))
    else:
        bottom_style = spec.get('bottom_style', 'trousers')
        for x, lift, shade in legs:
            c = shift(pants, shade)
            length = 4 if bottom_style == 'shorts' else 7 + lift
            box(img, x, 22, 4, length, c)
            rect(img, x + 1, 24, 1, max(1, length - 4), shift(c, 0.22))
            if bottom_style == 'jeans':
                rect(img, x + 1, 22, 2, 1, rgb('c4b68f'))
                rect(img, x, 27 + lift, 4, 1, shift(c, 0.4))
            elif bottom_style == 'chinos':
                rect(img, x + 2, 24, 1, 3 + lift, shift(c, -0.2))
            elif bottom_style == 'joggers':
                rect(img, x, 27 + lift, 4, 1, shift(c, -0.3))
    img = layers['shoes']
    for x, lift, shade in legs:
        c = shift(shoe, shade)
        heel, width = (x, 6) if side else (x - 1, 5)
        if spec.get('shoe_style') == 'sandals':
            rect(img, heel, 30 + lift, width, 1, c)
            rect(img, x + (3 if side else 1), 28 + lift, 1, 2, c)
            continue
        box(img, heel, 28 + lift, width, 3, c)
        rect(img, x + (1 if side else 0), 28 + lift, 3, 1, shift(c, 0.4))
        shoe_style = spec.get('shoe_style', 'sneakers')
        if shoe_style == 'boots':
            box(img, x, 26 + lift, 4, 4, c)
            rect(img, x + 1, 27 + lift, 1, 2, shift(c, 0.4))
        elif shoe_style == 'loafers':
            rect(img, x + (1 if side else 0), 29 + lift, 3, 1, shift(c, -0.3))

    img = layers['shirt']
    st = spec['top_style']
    x, width = (9, 8) if side else (7, 10)
    box(img, x, 16 + bob, width, 9, shirt)
    rect(img, x + 1, 17 + bob, 2, 6, shift(shirt, 0.25))
    rect(img, x + width - 2, 18 + bob, 1, 6, shift(shirt, -0.2))
    inner = rgb(spec.get('inner', 'f4e7c6'))
    if not back:
        rect(img, 11, 16 + bob, 3, 1, shift(shirt, -0.3))
        if st in ('blazer', 'cardigan', 'vest'):
            rect(img, 11, 17 + bob, 3, 6, inner)
            rect(img, 10, 18 + bob, 1, 3, shift(shirt, -0.2))
        if st == 'hoodie':
            rect(img, 10, 17 + bob, 1, 3, inner)
            rect(img, 14, 17 + bob, 1, 3, inner)
            rect(img, 10, 22 + bob, 5, 1, shift(shirt, -0.2))
        if st == 'overalls':
            rect(img, 8, 16 + bob, 8, 3, inner)
            for sx in (9, 14):
                rect(img, sx, 16 + bob, 1, 5, shirt)
                rect(img, sx, 19 + bob, 1, 1, rgb('f3c568'))
        if st == 'sweater':
            rect(img, 8, 21 + bob, 8, 1, shift(shirt, 0.3))
    else:
        if st == 'hoodie':
            box(img, 9, 16 + bob, 6, 4, shift(shirt, -0.15))
    for sx in ([14] if side else [5, 16]):
        swing = walk if sx < 12 else -walk
        box(img, sx, 17 + bob, 3, 7 + swing, shirt)
        if st == 'tee' or st == 'overalls':
            rect(layers['hands'], sx + 1, 20 + bob, 1, 3 + swing, skin)
        box(layers['hands'], sx, 23 + bob + swing, 3, 3, skin)
    # The head silhouette can change without moving the hair/hat anchor.
    img = layers['head']
    hx = 7 if side else 6
    wide = spec.get('head_style') == 'round'
    poly(img, [(hx + 2, 4 + bob), (hx + 10, 4 + bob), (hx + 12, 6 + bob),
               (hx + 12, 12 + bob), (hx + (10 if wide else 9), 15 + bob),
               (hx + 3, 15 + bob), (hx, 12 + bob), (hx, 6 + bob)], INK)
    rect(img, hx + 1, 6 + bob, 10, 7, skin)
    rect(img, hx + 3, 13 + bob, 6 if not wide else 7, 1, shift(skin, -0.12))
    rect(img, hx + 2, 6 + bob, 8, 2, shift(skin, 0.12))
    if spec.get('head_style') == 'square':
        box(img, hx, 5 + bob, 12, 10, skin)
        rect(img, hx + 1, 6 + bob, 10, 1, shift(skin, 0.12))
    elif spec.get('head_style') == 'heart':
        rect(img, hx, 11 + bob, 2, 2, INK)
        rect(img, hx + 10, 11 + bob, 2, 2, INK)
        rect(img, hx + 3, 14 + bob, 6, 1, INK)
        rect(img, hx + 4, 14 + bob, 4, 1, shift(skin, -0.12))
    # Ears belong to the skin layer, never the hairstyle's palette.
    if side:
        rect(img, 18, 10 + bob, 2, 2, skin)
    else:
        rect(img, 5, 10 + bob, 1, 2, skin)
        rect(img, 18, 10 + bob, 1, 2, skin)
    if not back:
        for ex in ([16] if side else [9, 14]):
            rect(img, ex, 9 + bob, 1, 3, INK)
            rect(img, ex, 9 + bob, 1, 1, rgb('fff2d5'))
        rect(img, 15 if side else 11, 13 + bob, 2, 1, rgb('a56857'))
    img = layers['hair']
    poly(img, [(6, 8 + bob), (6, 5 + bob), (8, 3 + bob), (15, 3 + bob),
               (18, 5 + bob), (19, 9 + bob), (16, 8 + bob), (13, 7 + bob),
               (10, 9 + bob), (8, 8 + bob), (7, 11 + bob), (5, 10 + bob)], INK)
    rect(img, 7, 5 + bob, 10, 2, hair)
    rect(img, 8, 4 + bob, 7, 1, hl)
    rect(img, 7, 7 + bob, 4, 1, hair)
    rect(img, 13, 7 + bob, 5, 1, hd)
    if back:
        rect(img, 7, 7 + bob, 10, 6, hair)
        rect(img, 9, 13 + bob, 6, 1, hd)
    if side:
        rect(img, 7, 7 + bob, 4, 5, hair)

    if style == 'curly':
        for cx, cy in ((6, 5), (9, 3), (13, 3), (16, 5), (5, 8)):
            box(img, cx, cy + bob, 4, 4, hair)
            rect(img, cx + 1, cy + 1 + bob, 2, 1, hl)
    elif style == 'bun':
        box(img, 9, 1 + bob, 6, 4, hair)
        rect(img, 10, 2 + bob, 3, 1, hl)
    elif style in ('long', 'wavy', 'bob'):
        rect(img, 6, 8 + bob, 2, 7 if style != 'bob' else 5, hair)
        if not side:
            rect(img, 17, 8 + bob, 2, 7 if style != 'bob' else 5, hair)
        if style == 'wavy':
            rect(img, 5, 12 + bob, 2, 3, hl)
    if style in ('bald', 'buzz'):
        layers['hair'] = Image(W, H)
        img = layers['hair']
        if style == 'buzz':
            rect(img, 8, 4 + bob, 8, 1, hair)
            rect(img, 7, 5 + bob, 10, 2, hair)
            if back:
                rect(img, 7, 7 + bob, 10, 5, hair)
    img = layers['accessory']
    acc = spec.get('accessory')
    if acc == 'glasses' and not back:
        for ex in ([14] if side else [7, 13]):
            rect(img, ex, 9 + bob, 5, 1, INK)
            rect(img, ex, 12 + bob, 5, 1, INK)
            rect(img, ex, 10 + bob, 1, 2, INK)
            rect(img, ex + 4, 10 + bob, 1, 2, INK)
        rect(img, 12, 10 + bob, 1, 1, INK)
    elif acc == 'headphones':
        rect(img, 8, 3 + bob, 8, 1, INK)
        for ex in ([7] if side else [5, 17]):
            box(img, ex, 8 + bob, 3, 5, rgb('d18567'))
    elif acc == 'scarf':
        rect(img, 9, 15 + bob, 7, 2, rgb(spec['accent']))
        rect(img, 14, 17 + bob, 2, 3, rgb(spec['accent']))
    img = layers['hat']
    if spec.get('hat') == 'beanie':
        c = rgb(spec['accent'])
        box(img, 6, 3 + bob, 13, 5, c)
        rect(img, 7, 2 + bob, 10, 2, c)
        rect(img, 6, 7 + bob, 13, 2, shift(c, 0.25))
        rect(img, 11, 1 + bob, 3, 2, shift(c, 0.3))
    return layers

WARDROBE = [
    dict(skin=SKINS[1], hair=HAIRS[0], hair_style='short', top='6d9089', top_style='tee', bottom='4a5a66', shoes='39423d'),
    dict(skin=SKINS[0], hair=HAIRS[1], hair_style='bob', top='c4826a', top_style='hoodie', bottom='3f4a52', shoes='2f3a35', accessory='glasses'),
    dict(skin=SKINS[3], hair=HAIRS[2], hair_style='curly', top='4d6377', top_style='blazer', inner='f2eddd', bottom='2f3a44', shoes='33302c'),
    dict(skin=SKINS[5], hair=HAIRS[3], hair_style='ponytail', top='dfb066', top_style='sweater', bottom='5c7484', bottom_style='skirt', shoes='7d5b3c'),
    dict(skin=SKINS[4], hair=HAIRS[4], hair_style='bun', top='6f9a63', top_style='cardigan', inner='efe8d6', bottom='d8cdb6', shoes='4a4038'),
    dict(skin=SKINS[0], hair=HAIRS[5], hair_style='wavy', top='7a6a9c', top_style='turtleneck', bottom='343c40', shoes='2c3330', accessory='headphones'),
    dict(skin=SKINS[2], hair=HAIRS[6], hair_style='buzz', top='5c7484', top_style='overalls', inner='ece5d2', bottom='5c7484', shoes='6b5a44', accessory='beanie', accent='c9705f'),
    dict(skin=SKINS[1], hair=HAIRS[7], hair_style='long', top='c9705f', top_style='vest', inner='f2eddd', bottom='45525a', shoes='3a3d37', accessory='scarf', accent='dfb066'),
]

# Hat is an independent slot, and presets exercise both supported head shapes.
WARDROBE[6].pop('accessory')
WARDROBE[6]['hat'] = 'beanie'
for i, spec in enumerate(WARDROBE):
    spec['head_style'] = 'round' if i % 2 else 'oval'


def build():
    sheet = Image(W * len(DIRECTIONS) * FRAMES, H * len(WARDROBE))
    sheets = {name: Image(sheet.w, sheet.h) for name in LAYERS}
    for c, spec in enumerate(WARDROBE):
        for d, direction in enumerate(DIRECTIONS):
            for f in range(FRAMES):
                layers = frame_layers(spec, direction, f)
                for name, art in layers.items():
                    x, y = (d * FRAMES + f) * W, c * H
                    sheets[name].paste(art, x, y)
                    sheet.paste(art, x, y)
    return sheet, WARDROBE, sheets
