#!/usr/bin/env bash
# Give a git worktree an office of its own: its own Compose project, and a block
# of ten published ports, so `docker compose up` here does not collide with the
# office already running in another worktree.
#
#   tools/worktree-env.sh <base-port> <compose-project> [source-env] > .env
#
# Worktrunk runs it from the pre-start hook in .config/wt.toml. Run it by hand
# for a worktree made with plain `git worktree add`. Anything in source-env that
# the block below does not define — SMTP credentials, LiveKit keys — is carried
# over, so a worktree inherits the settings of the office it branched from.
set -euo pipefail

base=${1:?usage: worktree-env.sh <base-port> <compose-project> [source-env]}
project=${2:?usage: worktree-env.sh <base-port> <compose-project> [source-env]}
source_env=${3:-}

if [[ ! $base =~ ^[0-9]+$ ]] || ((base < 1024 || base > 65530)); then
  echo "worktree-env.sh: $base is not a usable base port" >&2
  exit 1
fi

app=$base
vite=$((base + 1))
db=$((base + 2))
livekit=$((base + 3))
livekit_tcp=$((base + 4))
livekit_udp=$((base + 5))

generated=(
  COMPOSE_PROJECT_NAME APP_PORT APP_ORIGIN DEV_APP_ORIGIN PORT VITE_PORT DB_PORT
  LIVEKIT_PORT LIVEKIT_TCP_PORT LIVEKIT_UDP_PORT LIVEKIT_WS_URL
  DATABASE_URL TEST_DATABASE_URL E2E_BASE_URL
)

password=office
if [[ -n $source_env && -f $source_env ]]; then
  carried=$(sed -n 's/^[[:space:]]*POSTGRES_PASSWORD=//p' "$source_env" | tail -n 1)
  [[ -n $carried ]] && password=$carried
  printf '# Carried over from %s.\n' "$source_env"
  grep -vE "^[[:space:]]*($(
    IFS='|'
    echo "${generated[*]}"
  ))=" "$source_env" || true
  printf '\n'
fi

cat <<ENV
# Generated by tools/worktree-env.sh. This worktree owns ports $base-$((base + 9)),
# and Compose keeps its containers and its database volume under a project name
# of its own. Regenerate after moving the worktree; delete to fall back to the
# shared defaults. Host-side Node commands need these exported:
#
#   set -a; . ./.env; set +a
COMPOSE_PROJECT_NAME=$project
APP_PORT=$app
APP_ORIGIN=http://localhost:$app
PORT=$app
VITE_PORT=$vite
DB_PORT=$db
LIVEKIT_PORT=$livekit
LIVEKIT_TCP_PORT=$livekit_tcp
LIVEKIT_UDP_PORT=$livekit_udp
LIVEKIT_WS_URL=ws://localhost:$livekit
DATABASE_URL=postgres://office:$password@localhost:$db/office
TEST_DATABASE_URL=postgres://office:$password@localhost:$db/office
E2E_BASE_URL=http://localhost:$app
ENV
